# Generated by Django 4.1.5 on 2023-02-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_usermodel_options_alter_usermodel_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='lastName',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(max_length=64),
        ),
    ]
