# Generated by Django 4.1.5 on 2023-02-06 12:57

from django.db import migrations
import stackOverFlow.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mypost'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', stackOverFlow.manager.UserManager()),
            ],
        ),
    ]
